{
 "title": "SmartGreenHouse",
 "time": { "from": "2022-07-23T22:31:43.978Z", "to": "2022-07-25T09:27:47.562Z" },
 "templating": {
  "list": [
   { "name": "query0" }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temperature ",
   "type": "timeseries",
   "description": "nodo 2",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  sample\nFROM temperature\nWHERE\n  machineid = 2 \nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Temperature ",
   "type": "timeseries",
   "description": "nodo 3\n",
   "gridPos": { "h": 11, "w": 10, "x": 10, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  sample\nFROM temperature\nWHERE\n  machineid = 3\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Temperature ",
   "type": "bargauge",
   "description": "nodo 3\n",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  sample\nFROM temperature\nWHERE\n  machineid = 3\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Light",
   "type": "timeseries",
   "description": "nodo 2",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  sample\nFROM light\nWHERE\n  machineid = 2\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Light",
   "type": "timeseries",
   "description": "nodo 3",
   "gridPos": { "h": 9, "w": 10, "x": 10, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  sample\nFROM light\nWHERE\n  machineid = 3\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "description": "nodo 2",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  sample\nFROM humidity\nWHERE\n  machineid = 2 \nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "description": "nodo 3",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  sample\nFROM humidity\nWHERE\n  machineid = 3\nORDER BY timestamp"
    }
   ]
  }
 ]
}